version: '3.9'

services:
  backend:
    build:
      context: ./VibeTune.Api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./VibeTune.Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
